### PR TITLE
Solution

### PR DESCRIPTION
**Pull request by D0mln0**
{EBDCD4CC-667B-4F0B-A26A-616A588B6C7B}

### CODE REVIEW

**Review by vasylhnatiuk — CHANGES_REQUESTED** [review]
delete venv, idea, db.sqlite3

**Comment by D0mln0** [comment]
delete from file or add to gitignore, because i put them to gitignore(as it was said in task)

**Review by vasylhnatiuk — CHANGES_REQUESTED** [review]
delete venv, idea, db.sqlite3 from pull request

**Comment by D0mln0** [comment]
merging with modified gitignore file

**Pull request closed without merging**
