### PR TITLE
'Solution'

### PR DESCRIPTION
**Pull request by dsokolovskiy**
after commit, I get a message about a large number of files :(

### CODE REVIEW

**Comment by dsokolovskiy** [comment]
image

**Comment by dsokolovskiy** [comment]
image
image
image
image

**Review by DevSpaciX — CHANGES_REQUESTED** [review]
Seems like you added so much unnecessery files . Remove them pls

**Comment by dsokolovskiy** [comment]
> Seems like you added so much unnecessery files . Remove them pls

okay, ty
how i can remove this file?

**Pull request closed without merging**
