### PR TITLE
py-taxi-service-startproject

### PR DESCRIPTION
**Pull request by muriakula**

### CODE REVIEW

**Comment by muriakula** [comment]
Screenshot 2023-08-09 122645

**Comment by muriakula** [comment]
Screenshot 2023-08-09 122315

**Comment by muriakula** [comment]
Screenshot 2023-08-09 122259

**Comment by muriakula** [comment]
Screenshot 2023-08-09 122028

**Review by YukihiroSM — APPROVED** [review]
Nicely done!

**Pull request closed without merging**
